const planity='https://www.planity.com/etoile-beaute-studio-72100-le-mans';
const pages={
 '/soin-visage-japonais-menard-au-mans':{eyebrow:'SOINS VISAGE JAPONAIS · MENARD',title:'Soin visage japonais Menard au Mans',intro:'Des rituels d’exception pensés pour hydrater, illuminer et révéler l’éclat naturel de votre peau.',menu:'Les soins visage Menard',cards:[['Soin Signature Lumineux TK','Soin hydratation intensif à l’extrait de gardénia SP pour une peau souple et lumineuse.','89 € · 1h10'],['Lumière Pure Saranari','Un soin anti-âge qui associe hydratation profonde, élasticité et confort.','125 € · 1h30'],['Éclat Suprême Fairlucent','Un rituel illuminant pour une texture lissée et un teint frais.','109 € · 1h20'],['Anti-Âge Global Embellir','Soin haute performance pour une peau visiblement plus confortable et éclatante.','145 €'],['Quatre Saisons Menard','Un voyage sensoriel complet alliant relaxation profonde et effet liftant.','169 €']]},
 '/maquillage-permanent-levres-eyeliner':{eyebrow:'MAQUILLAGE PERMANENT',title:'Maquillage permanent : lèvres & eyeliner',intro:'Sublimez vos traits grâce à des gestes précis, des pigments de qualité et un résultat naturellement harmonieux.',menu:'Lèvres & eyeliner',cards:[['Création eyeliner','Un trait personnalisé pour intensifier le regard tout en respectant votre morphologie.','200 €'],['Dégradé lèvres','Une mise en couleur douce pour des lèvres définies et lumineuses.','350 €'],['Remplissage complet','Une couleur plus présente et homogène pour sublimer les lèvres.','450 €'],['Retouche eyeliner après 6 mois','Pour entretenir votre résultat dans le temps.','75 €'],['Retouche lèvres après 6 mois','Pour conserver un résultat harmonieux.','110–120 €']]},
 '/maquillage-sourcils':{eyebrow:'MAQUILLAGE PERMANENT',title:'Maquillage permanent des sourcils',intro:'Redessinez et intensifiez vos sourcils avec une prestation personnalisée, adaptée à votre visage et à vos envies.',menu:'Sourcils',cards:[['Épilation & restructuration','Un regard structuré avec une ligne de sourcil adaptée.','32 €'],['Épilation entretien mensuel','Gardez une ligne nette et harmonieuse.','22 €'],['Microblading / Microshading','Un résultat naturel et durable, défini lors du rendez-vous conseil.','300 €'],['Micro-Grayling','Effet ombré et poil pour un rendu raffiné.','350 €'],['Retouche après 6 mois','Entretien selon votre prestation et votre évolution.','100–110 €']]},
 '/massage-corps-californien-kobido':{eyebrow:'MASSAGES & BIEN-ÊTRE',title:'Massages corps & Kobido visage',intro:'Une pause pour dénouer les tensions, retrouver de la légèreté et profiter d’un moment profondément ressourçant.',menu:'Les massages',cards:[['Massage Californien','Un massage enveloppant, doux et relaxant pour le corps.','Réservation sur Planity'],['Massage dos & épaules','Un soin ciblé pour libérer les zones de tension du haut du corps.','Réservation sur Planity'],['Kobido visage','Un massage visage inspiré des techniques japonaises pour un moment de détente et d’éclat.','Disponible à partir du 20 septembre 2026']]},
 '/soins-des-mains-gommage-corps':{eyebrow:'SOINS CORPS & MAINS',title:'Soins des mains & gommage corps',intro:'Des rituels dédiés au confort de la peau, à la douceur et au bien-être du corps.',menu:'La carte corps & mains',cards:[['Soin des mains','Un soin nourrissant et relaxant comprenant bain, gommage, massage et masque.','45 € · 30 min'],['Gommage corps','Un rituel exfoliant pour une peau plus douce, lisse et confortable.','55 € · 45 min']]}
};
const slug='/' + location.pathname.split('/').filter(Boolean).at(-1);const page=pages[slug]||pages['/soin-visage-japonais-menard-au-mans'];document.title=`${page.title} | Etoile Beauté Studio`;document.querySelector('#eyebrow').textContent=page.eyebrow;document.querySelector('#title').textContent=page.title;document.querySelector('#intro').textContent=page.intro;document.querySelector('#menu-title').textContent=page.menu;document.querySelector('#cards').innerHTML=page.cards.map(([name,text,price])=>`<article class="card"><h3>${name}</h3><p>${text}</p><span class="price">${price}</span></article>`).join('');document.querySelectorAll('[data-planity]').forEach(a=>{a.href=planity;a.target='_blank';a.rel='noopener'});
